#!/usr/bin/env bash

# Remove the default configuration file in /etc/nginx/sites-enabled/
rm /etc/nginx/sites-enabled/default

# Create a symbolic link to the default configuration file in /etc/nginx/sites-available/
ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default

# Restart Nginx to apply the configuration changes
service nginx restart
