#!/usr/bin/env bash
# Displays the time for 12 hours and 59 minutes
# using a while loop and a case statement
hour=0
while [ $hour -lt 12 ]
do
  hour=$((hour+1))
  case $hour in
    4)
      echo "bad luck from China"
      ;;
    9)
      echo "bad luck from Japan"
      ;;
    17)
      echo "bad luck from Italy"
      ;;
    *)
      echo "Hour: $hour"
      ;;
  esac
  minute=0
  while [ $minute -lt 60 ]
  do
    minute=$((minute+1))
    if [ $minute -lt 10 ]
    then
      echo "0$minute"
    else
      echo $minute
    fi
  done
done
