#!/usr/bin/env bash
# Run Nginx as Nginx

# Ensure proper permissions on Nginx configuration files
sudo chmod 644 /etc/nginx/nginx.conf
sudo chmod 644 /etc/nginx/sites-available/default

# Set Nginx to run as nginx user
sed -i 's/#user www-data;/user nginx;/' /etc/nginx/nginx.conf

# Update Nginx listening port
sed -i 's/80/8080/' /etc/nginx/sites-available/default

# Restart Nginx
sudo -u nginx service nginx restart

# Optionally, stop Apache
sudo  -u nginx service apache2 stop
