#!/usr/bin/env bash
# Run Nginx as Nginx
sed -i 's/user\s*\(.*\);/user nginx;/' /etc/nginx/nginx.conf
sed -i 's/listen\s*\(.*\);/listen *:8080;/' /etc/nginx/sites-available/default
sed -i 's/#user www-data;/user nginx;/g' /etc/nginx/nginx.conf
chmod ugo+wrx /etc/apache2/ports.conf /etc/nginx/nginx.conf
sudo -u nginx service nginx restart
