#!/usr/bin/env bash
# This script configures Nginx to proxy requests to a Gunicorn instance for the number_odd_or_even route

# Create a new Nginx configuration file for the number_odd_or_even route
sudo tee /etc/nginx/sites-available/airbnb_dynamic << EOF
server {
    listen 80;
    listen [::]:80;

    location /airbnb-dynamic/number_odd_or_even/ {
        proxy_pass http://0.0.0.0:5001;
        proxy_set_header Host \$host;
        proxy_set_header X-Real-IP \$remote_addr;
        proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto \$scheme;
    }
}
EOF

# Create a symbolic link to enable the configuration
sudo ln -s /etc/nginx/sites-available/airbnb_dynamic /etc/nginx/sites-enabled/

# Restart Nginx to apply the changes
sudo systemctl restart nginx

echo "Nginx configuration for number_odd_or_even route completed."
